### ISSUE TITLE
Power Failure

### ISSUE THREAD

**Issue by Photographix** [fopina/pokebox#2]
Hello, is the project still working or orphaned? Just so I don't spend unnecessary time troubleshooting. 

After adjusting some things in the settings (network, timezone, allowed hosts) I was able to get the Djago interface to run. Unfortunately no found devices are displayed. The log always ends with "**Power Failure**". If I execute **nmap -sn 192.168.x.x** in the shell of the container, I have a listing of the devices in the shell. Where could be the error? I don't know anything about Python and Django :-/

Pokebox runs in current Docker release on virtual Centos x64

**Comment by fopina** [comment]
Hi nice to see this would be useful for others but little after I finished this (very) alpha version, I started using home assistant and its integration with routers device list, so I did not maintain it anymore...

I did have in my ToDo list to refactor this to single go binary but never go to it.

That being said, if you do want to work on it, let me know, I can update the README to point to your fork and archive it

**Comment by fopina** [comment]
On a related note/suggestion, Fing has released a windows/OS X client that might be interesting to try to run in a docker+wine(+qemu if on Pi) and make use of their app/notifications/service
